version: "3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patients
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    ports:
      - "3306:3306"
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
